# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/srikur/Documents/GitHub/NoteWeaver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/srikur/Documents/GitHub/NoteWeaver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/srikur/Documents/GitHub/NoteWeaver/CMakeFiles /Users/srikur/Documents/GitHub/NoteWeaver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/srikur/Documents/GitHub/NoteWeaver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NoteWeaver

# Build rule for target.
NoteWeaver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NoteWeaver
.PHONY : NoteWeaver

# fast build rule for target.
NoteWeaver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/build
.PHONY : NoteWeaver/fast

cpp/Score.o: cpp/Score.cpp.o
.PHONY : cpp/Score.o

# target to build an object file
cpp/Score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Score.cpp.o
.PHONY : cpp/Score.cpp.o

cpp/Score.i: cpp/Score.cpp.i
.PHONY : cpp/Score.i

# target to preprocess a source file
cpp/Score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Score.cpp.i
.PHONY : cpp/Score.cpp.i

cpp/Score.s: cpp/Score.cpp.s
.PHONY : cpp/Score.s

# target to generate assembly for a file
cpp/Score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Score.cpp.s
.PHONY : cpp/Score.cpp.s

cpp/Sheet.o: cpp/Sheet.cpp.o
.PHONY : cpp/Sheet.o

# target to build an object file
cpp/Sheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Sheet.cpp.o
.PHONY : cpp/Sheet.cpp.o

cpp/Sheet.i: cpp/Sheet.cpp.i
.PHONY : cpp/Sheet.i

# target to preprocess a source file
cpp/Sheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Sheet.cpp.i
.PHONY : cpp/Sheet.cpp.i

cpp/Sheet.s: cpp/Sheet.cpp.s
.PHONY : cpp/Sheet.s

# target to generate assembly for a file
cpp/Sheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Sheet.cpp.s
.PHONY : cpp/Sheet.cpp.s

cpp/Utilities.o: cpp/Utilities.cpp.o
.PHONY : cpp/Utilities.o

# target to build an object file
cpp/Utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Utilities.cpp.o
.PHONY : cpp/Utilities.cpp.o

cpp/Utilities.i: cpp/Utilities.cpp.i
.PHONY : cpp/Utilities.i

# target to preprocess a source file
cpp/Utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Utilities.cpp.i
.PHONY : cpp/Utilities.cpp.i

cpp/Utilities.s: cpp/Utilities.cpp.s
.PHONY : cpp/Utilities.s

# target to generate assembly for a file
cpp/Utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/cpp/Utilities.cpp.s
.PHONY : cpp/Utilities.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NoteWeaver.dir/build.make CMakeFiles/NoteWeaver.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NoteWeaver"
	@echo "... cpp/Score.o"
	@echo "... cpp/Score.i"
	@echo "... cpp/Score.s"
	@echo "... cpp/Sheet.o"
	@echo "... cpp/Sheet.i"
	@echo "... cpp/Sheet.s"
	@echo "... cpp/Utilities.o"
	@echo "... cpp/Utilities.i"
	@echo "... cpp/Utilities.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

